
default: help
.PHONY: default

help:
	@echo 'Usage:'
	@echo '	$$ make [action]'
	@echo
	@echo 'Ex:'
	@echo '	$$ make'
	@echo '	$$ make help'
	@echo
	@echo '	$$ make install'
	@echo
.PHONY: help




install:
	@./install.sh
.PHONY: install




apt-install:
	sudo apt-get install yt-dlp
.PHONY: apt-install
